---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventstreams-catalog
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  displayName: ibm-eventstreams-3.5.0
  publisher: IBM
  # image: icr.io/cpopen/ibm-eventstreams-catalog@sha256:4cf53a33dee2e8e54e3c8b04a396cb0555a6bdd5cdcb91aed5d81716ab37b179
  image: icr.io/cpopen/ibm-eventstreams-catalog@sha256:1b97556a63d33910c59332942eae0cf26a8c02c3e1690d7765e0251980317b3a
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "ibm-eventstreams"
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: "v3.5"
  name: "ibm-eventstreams"
  source: "ibm-eventstreams-catalog"
  sourceNamespace: openshift-marketplace
  # installPlanApproval: Manual
