apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventendpointmanagement
  namespace: openshift-operators  
  labels:
    backup.integration.ibm.com/component: subscription        
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: v11.3
  name: ibm-eventendpointmanagement
  source: ibm-eventendpointmanagement-catalog
  sourceNamespace: openshift-marketplace